### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [trifl/Chirp#7]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by andreamazz** [comment]
You can point your podfile to my fork for now:

```
pod 'Chrip', git: 'https://github.com/andreamazz/Chirp'
```

@trifl let me know if you need help maintaining this lib, I'd be happy to pitch in.

**Comment by lfarah** [comment]
Thanks @andreamazz... Do you want to send a pull request of your branch here?

**Comment by andreamazz** [comment]
Sure, let me polish the branch a little, right now it was just a temporary fix.
I'll open a PR as soon as possible.

**Comment by jpmcglone** [comment]
I'm sorry I abandoned the repo for so long! I updated the latest code to work with Swift 5 and bumped the library to 1.2.0

```
pod 'Chirp' 
```
is now 1.2.0
